--DROP TABLE Brands;

CREATE TABLE Brands (
   id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   code CHAR(32),
   name VARCHAR(255),
   link VARCHAR(1024)
);

CREATE UNIQUE INDEX Brands_IDX1 ON Brands (code);
